### ISSUE TITLE
STAGEs Crashed

### ISSUE THREAD

**Issue by CollynKellogg** [kuanrongchan/STAGES#5]
I was using STAGEs to analyze an RNA Seq data set, and during my GSEA analysis it crashed suddenly, and even restarting my computer and reopening the web page, I am getting an error report and can not see or do anything. I've tried clearing cookies and cache and nothing has helped.

**Comment by kuanrongchan** [comment]
Thank you for trying STAGEs. GSEA on big datasets can be resource intensive which may cause delays in generating output. If this problem persists, we recommend running STAGEs locally, and the instructions can be found in the readme file in GitHub. Otherwise, you may download the .gmt files from our GitHub and consider GSEApy and clusterprofiler for analysis.
